[package]
name = "metro"
version = "0.1.0"
authors = ["Frank A. Stevenson <frank.stevenson@xxx>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.4.1"
rand = "0.7.3"
pbr = "1.0.3"
